// 헤더에 보여 줄 사자성어 목록. 네이버 한자사전에서 자주 찾는 성어 위주로
// 골랐다(가나다순 200개). 실시간 인기 순위를 받아 오려면 비공개 API와 호스트 권한이 필요해서,
// 목록을 확장 안에 넣어 두고 클릭했을 때만 사전으로 넘긴다.
// 한자는 국내에서 쓰는 자형(晩·爲·靑·敎 등)을 따른다.
const IDIOMS = [
  { hanja: "刻舟求劍", hangul: "각주구검", meaning: "융통성 없이 낡은 방식만 고집하는 어리석음" },
  { hanja: "感之德之", hangul: "감지덕지", meaning: "과분하다고 여겨 매우 고맙게 여김" },
  { hanja: "甲論乙駁", hangul: "갑론을박", meaning: "서로 제 주장을 내세우며 남의 주장을 반박함" },
  { hanja: "改過遷善", hangul: "개과천선", meaning: "지난날의 잘못을 고치고 착하게 됨" },
  { hanja: "去頭截尾", hangul: "거두절미", meaning: "앞뒤 군더더기를 빼고 요점만 말함" },
  { hanja: "乾坤一擲", hangul: "건곤일척", meaning: "운명을 걸고 단판으로 승부를 겨룸" },
  { hanja: "牽强附會", hangul: "견강부회", meaning: "이치에 맞지 않는 말을 억지로 끌어다 제 주장에 맞춤" },
  { hanja: "見物生心", hangul: "견물생심", meaning: "물건을 보면 그것을 갖고 싶은 마음이 생김" },
  { hanja: "結者解之", hangul: "결자해지", meaning: "일을 벌인 사람이 그 일을 해결해야 함" },
  { hanja: "結草報恩", hangul: "결초보은", meaning: "죽어서도 잊지 않고 은혜를 갚음" },
  { hanja: "輕擧妄動", hangul: "경거망동", meaning: "경솔하고 분별없이 행동함" },
  { hanja: "鷄卵有骨", hangul: "계란유골", meaning: "운이 나쁜 사람은 좋은 기회를 만나도 일이 잘 안 됨" },
  { hanja: "孤軍奮鬪", hangul: "고군분투", meaning: "남의 도움 없이 힘에 벅찬 일을 해냄" },
  { hanja: "苦盡甘來", hangul: "고진감래", meaning: "고생 끝에 즐거움이 옴" },
  { hanja: "空中樓閣", hangul: "공중누각", meaning: "근거나 토대가 없는 사물이나 생각" },
  { hanja: "過猶不及", hangul: "과유불급", meaning: "정도를 지나침은 미치지 못함과 같음" },
  { hanja: "管鮑之交", hangul: "관포지교", meaning: "형편에 관계없이 서로 믿고 아끼는 두터운 우정" },
  { hanja: "刮目相對", hangul: "괄목상대", meaning: "남의 학식이나 재주가 몰라볼 만큼 부쩍 늚" },
  { hanja: "巧言令色", hangul: "교언영색", meaning: "아첨하는 말과 알랑거리는 태도" },
  { hanja: "敎學相長", hangul: "교학상장", meaning: "가르치고 배우면서 스승과 제자가 함께 성장함" },
  { hanja: "口蜜腹劍", hangul: "구밀복검", meaning: "말로는 친한 척하나 속으로는 해칠 생각을 품음" },
  { hanja: "九死一生", hangul: "구사일생", meaning: "죽을 고비를 여러 번 넘기고 겨우 살아남" },
  { hanja: "群鷄一鶴", hangul: "군계일학", meaning: "많은 사람 가운데 뛰어난 한 사람" },
  { hanja: "權謀術數", hangul: "권모술수", meaning: "목적을 위해 수단과 방법을 가리지 않는 술책" },
  { hanja: "捲土重來", hangul: "권토중래", meaning: "실패한 뒤 힘을 가다듬어 다시 도전함" },
  { hanja: "近墨者黑", hangul: "근묵자흑", meaning: "나쁜 사람을 가까이하면 그 버릇에 물들기 쉬움" },
  { hanja: "金科玉條", hangul: "금과옥조", meaning: "소중히 여겨 꼭 지켜야 할 법칙이나 규범" },
  { hanja: "錦上添花", hangul: "금상첨화", meaning: "좋은 일 위에 또 좋은 일이 더해짐" },
  { hanja: "錦衣還鄕", hangul: "금의환향", meaning: "출세하여 고향에 돌아옴" },
  { hanja: "金枝玉葉", hangul: "금지옥엽", meaning: "귀한 자손이나 아주 귀하게 여기는 자식" },
  { hanja: "起死回生", hangul: "기사회생", meaning: "거의 죽을 뻔하다가 다시 살아남" },
  { hanja: "難兄難弟", hangul: "난형난제", meaning: "누가 더 낫다고 하기 어려울 만큼 비슷함" },
  { hanja: "囊中之錐", hangul: "낭중지추", meaning: "재능이 뛰어난 사람은 숨어 있어도 저절로 드러남" },
  { hanja: "內憂外患", hangul: "내우외환", meaning: "안팎으로 겹친 여러 가지 근심과 걱정" },
  { hanja: "怒發大發", hangul: "노발대발", meaning: "몹시 노하여 크게 성을 냄" },
  { hanja: "多多益善", hangul: "다다익선", meaning: "많으면 많을수록 더욱 좋음" },
  { hanja: "多才多能", hangul: "다재다능", meaning: "재주와 능력이 여러 방면에 걸쳐 있음" },
  { hanja: "單刀直入", hangul: "단도직입", meaning: "군말 없이 바로 요점으로 들어감" },
  { hanja: "大器晩成", hangul: "대기만성", meaning: "큰 인물은 오랜 공을 들여 늦게 이루어짐" },
  { hanja: "大同小異", hangul: "대동소이", meaning: "큰 차이 없이 거의 같음" },
  { hanja: "獨不將軍", hangul: "독불장군", meaning: "무슨 일이든 제 생각대로만 혼자 처리하는 사람" },
  { hanja: "同價紅裳", hangul: "동가홍상", meaning: "같은 값이면 더 좋은 것을 고름" },
  { hanja: "同苦同樂", hangul: "동고동락", meaning: "괴로움과 즐거움을 함께함" },
  { hanja: "東問西答", hangul: "동문서답", meaning: "물음과 전혀 상관없는 엉뚱한 대답" },
  { hanja: "同病相憐", hangul: "동병상련", meaning: "어려운 처지의 사람끼리 서로 가엾게 여김" },
  { hanja: "東奔西走", hangul: "동분서주", meaning: "사방으로 이리저리 몹시 바쁘게 돌아다님" },
  { hanja: "同床異夢", hangul: "동상이몽", meaning: "겉으로는 함께하면서 속으로는 각기 딴생각을 함" },
  { hanja: "燈下不明", hangul: "등하불명", meaning: "등잔 밑이 어둡듯 가까운 것을 도리어 잘 모름" },
  { hanja: "燈火可親", hangul: "등화가친", meaning: "서늘한 가을밤은 등불을 가까이하여 글 읽기에 좋음" },
  { hanja: "磨斧爲針", hangul: "마부위침", meaning: "아무리 어려운 일도 끊임없이 노력하면 이룸" },
  { hanja: "馬耳東風", hangul: "마이동풍", meaning: "남의 말을 귀담아듣지 않고 흘려버림" },
  { hanja: "莫逆之友", hangul: "막역지우", meaning: "허물없이 아주 친한 벗" },
  { hanja: "萬事亨通", hangul: "만사형통", meaning: "모든 일이 뜻한 대로 잘됨" },
  { hanja: "滿身瘡痍", hangul: "만신창이", meaning: "온몸이 상처투성이가 되거나 일이 엉망이 됨" },
  { hanja: "名實相符", hangul: "명실상부", meaning: "이름과 실제가 서로 들어맞음" },
  { hanja: "目不忍見", hangul: "목불인견", meaning: "눈 뜨고 차마 볼 수 없을 만큼 딱하거나 참혹함" },
  { hanja: "無用之物", hangul: "무용지물", meaning: "쓸모없는 물건이나 사람" },
  { hanja: "文房四友", hangul: "문방사우", meaning: "종이, 붓, 먹, 벼루의 네 가지 문방구" },
  { hanja: "門前成市", hangul: "문전성시", meaning: "찾아오는 사람이 많아 집 앞이 시장처럼 붐빔" },
  { hanja: "拍掌大笑", hangul: "박장대소", meaning: "손뼉을 치며 크게 웃음" },
  { hanja: "博學多識", hangul: "박학다식", meaning: "학식이 넓고 아는 것이 많음" },
  { hanja: "半信半疑", hangul: "반신반의", meaning: "얼마쯤 믿으면서도 한편으로는 의심함" },
  { hanja: "拔本塞源", hangul: "발본색원", meaning: "좋지 않은 일의 근본 원인을 아예 뿌리 뽑음" },
  { hanja: "傍若無人", hangul: "방약무인", meaning: "곁에 아무도 없는 것처럼 함부로 행동함" },
  { hanja: "背恩忘德", hangul: "배은망덕", meaning: "남에게 입은 은혜를 저버림" },
  { hanja: "白骨難忘", hangul: "백골난망", meaning: "죽어서도 잊지 못할 만큼 큰 은혜를 입음" },
  { hanja: "百年大計", hangul: "백년대계", meaning: "먼 앞날까지 내다보고 세우는 큰 계획" },
  { hanja: "百戰百勝", hangul: "백전백승", meaning: "싸울 때마다 모두 이김" },
  { hanja: "百害無益", hangul: "백해무익", meaning: "해롭기만 하고 이로운 것이 없음" },
  { hanja: "父傳子傳", hangul: "부전자전", meaning: "아버지의 성품이나 버릇이 아들에게 그대로 전해짐" },
  { hanja: "附和雷同", hangul: "부화뇌동", meaning: "줏대 없이 남의 의견을 따라 움직임" },
  { hanja: "粉骨碎身", hangul: "분골쇄신", meaning: "몸이 부서질 만큼 정성과 힘을 다함" },
  { hanja: "不撤晝夜", hangul: "불철주야", meaning: "밤낮을 가리지 않고 일에 몰두함" },
  { hanja: "非一非再", hangul: "비일비재", meaning: "같은 일이 한두 번이 아니고 아주 많음" },
  { hanja: "四面楚歌", hangul: "사면초가", meaning: "사방이 적으로 둘러싸여 도움받을 곳이 없는 처지" },
  { hanja: "砂上樓閣", hangul: "사상누각", meaning: "기초가 약해 오래 버티지 못할 일" },
  { hanja: "事必歸正", hangul: "사필귀정", meaning: "모든 일은 결국 바른길로 돌아감" },
  { hanja: "山戰水戰", hangul: "산전수전", meaning: "세상의 온갖 고생과 어려움을 다 겪음" },
  { hanja: "殺身成仁", hangul: "살신성인", meaning: "자기 몸을 희생하여 옳은 일을 이룸" },
  { hanja: "三顧草廬", hangul: "삼고초려", meaning: "인재를 얻기 위해 참을성 있게 정성을 다함" },
  { hanja: "桑田碧海", hangul: "상전벽해", meaning: "뽕밭이 바다가 될 만큼 세상이 몰라보게 바뀜" },
  { hanja: "塞翁之馬", hangul: "새옹지마", meaning: "인생의 길흉화복은 변화가 많아 미리 헤아리기 어려움" },
  { hanja: "先見之明", hangul: "선견지명", meaning: "앞일을 미리 내다보는 밝은 지혜" },
  { hanja: "雪上加霜", hangul: "설상가상", meaning: "어려운 일이 겹쳐 일어남" },
  { hanja: "小貪大失", hangul: "소탐대실", meaning: "작은 것을 탐하다가 큰 것을 잃음" },
  { hanja: "束手無策", hangul: "속수무책", meaning: "어찌할 도리가 없어 꼼짝 못 함" },
  { hanja: "袖手傍觀", hangul: "수수방관", meaning: "간섭하거나 거들지 않고 그저 보고만 있음" },
  { hanja: "守株待兎", hangul: "수주대토", meaning: "한 가지만 고집하여 변통할 줄 모르는 어리석음" },
  { hanja: "脣亡齒寒", hangul: "순망치한", meaning: "입술이 없으면 이가 시리듯 서로 떼어 놓을 수 없는 관계" },
  { hanja: "始終一貫", hangul: "시종일관", meaning: "처음부터 끝까지 한결같음" },
  { hanja: "識字憂患", hangul: "식자우환", meaning: "아는 것이 도리어 근심거리가 됨" },
  { hanja: "信賞必罰", hangul: "신상필벌", meaning: "공이 있으면 반드시 상을, 죄가 있으면 반드시 벌을 줌" },
  { hanja: "身土不二", hangul: "신토불이", meaning: "제 땅에서 난 것이 제 몸에 잘 맞음" },
  { hanja: "心機一轉", hangul: "심기일전", meaning: "마음가짐을 새롭게 하여 완전히 달라짐" },
  { hanja: "深思熟考", hangul: "심사숙고", meaning: "깊이 잘 생각함" },
  { hanja: "十匙一飯", hangul: "십시일반", meaning: "여럿이 조금씩 힘을 모으면 한 사람을 쉽게 도울 수 있음" },
  { hanja: "十中八九", hangul: "십중팔구", meaning: "열에 여덟이나 아홉, 거의 틀림없음" },
  { hanja: "阿鼻叫喚", hangul: "아비규환", meaning: "여러 사람이 참혹한 지경에 빠져 울부짖는 모습" },
  { hanja: "我田引水", hangul: "아전인수", meaning: "자기에게만 이롭게 생각하거나 행동함" },
  { hanja: "安貧樂道", hangul: "안빈낙도", meaning: "가난한 생활 속에서도 편안한 마음으로 도를 즐김" },
  { hanja: "眼下無人", hangul: "안하무인", meaning: "교만하여 다른 사람을 업신여김" },
  { hanja: "愛之重之", hangul: "애지중지", meaning: "매우 사랑하고 소중히 여김" },
  { hanja: "藥房甘草", hangul: "약방감초", meaning: "어떤 일에나 빠짐없이 끼어드는 사람이나 꼭 필요한 것" },
  { hanja: "弱肉强食", hangul: "약육강식", meaning: "약한 자가 강한 자에게 먹힘" },
  { hanja: "羊頭狗肉", hangul: "양두구육", meaning: "겉보기만 그럴듯하고 속은 변변치 않음" },
  { hanja: "漁父之利", hangul: "어부지리", meaning: "둘이 다투는 사이에 엉뚱한 제삼자가 이익을 얻음" },
  { hanja: "語不成說", hangul: "어불성설", meaning: "말이 조금도 이치에 맞지 않음" },
  { hanja: "言中有骨", hangul: "언중유골", meaning: "예사로운 말 속에 단단한 속뜻이 있음" },
  { hanja: "言行一致", hangul: "언행일치", meaning: "말과 행동이 서로 같음" },
  { hanja: "易地思之", hangul: "역지사지", meaning: "처지를 바꾸어 생각해 봄" },
  { hanja: "緣木求魚", hangul: "연목구어", meaning: "나무에 올라 물고기를 구하듯 불가능한 일을 하려 함" },
  { hanja: "五里霧中", hangul: "오리무중", meaning: "갈피를 잡을 수 없거나 행방을 알 수 없음" },
  { hanja: "烏飛梨落", hangul: "오비이락", meaning: "우연히 때가 겹쳐 억울하게 의심을 받음" },
  { hanja: "烏合之卒", hangul: "오합지졸", meaning: "규율이나 통일성 없이 모인 무리" },
  { hanja: "溫故知新", hangul: "온고지신", meaning: "옛것을 익혀 새것을 앎" },
  { hanja: "臥薪嘗膽", hangul: "와신상담", meaning: "뜻을 이루기 위해 온갖 괴로움을 참고 견딤" },
  { hanja: "外柔內剛", hangul: "외유내강", meaning: "겉은 부드러우나 속은 곧고 굳셈" },
  { hanja: "龍頭蛇尾", hangul: "용두사미", meaning: "시작은 거창하나 끝이 보잘것없음" },
  { hanja: "愚公移山", hangul: "우공이산", meaning: "꾸준히 노력하면 어떤 일이든 이룰 수 있음" },
  { hanja: "優柔不斷", hangul: "우유부단", meaning: "망설이기만 하고 결단을 내리지 못함" },
  { hanja: "雨後竹筍", hangul: "우후죽순", meaning: "어떤 일이 한때에 많이 생겨남" },
  { hanja: "危機一髮", hangul: "위기일발", meaning: "여유가 조금도 없이 몹시 위태로운 순간" },
  { hanja: "有備無患", hangul: "유비무환", meaning: "미리 준비해 두면 걱정할 것이 없음" },
  { hanja: "類類相從", hangul: "유유상종", meaning: "같은 무리끼리 서로 어울림" },
  { hanja: "意氣投合", hangul: "의기투합", meaning: "마음이나 뜻이 서로 맞음" },
  { hanja: "異口同聲", hangul: "이구동성", meaning: "여러 사람의 말이 한결같음" },
  { hanja: "以心傳心", hangul: "이심전심", meaning: "말하지 않아도 마음과 마음으로 뜻이 통함" },
  { hanja: "以熱治熱", hangul: "이열치열", meaning: "열은 열로써 다스림" },
  { hanja: "因果應報", hangul: "인과응보", meaning: "행한 대로 그 결과가 돌아옴" },
  { hanja: "人之常情", hangul: "인지상정", meaning: "사람이면 누구나 가지는 보통의 마음" },
  { hanja: "一擧兩得", hangul: "일거양득", meaning: "한 가지 일로 두 가지 이익을 얻음" },
  { hanja: "一目瞭然", hangul: "일목요연", meaning: "한눈에 분명히 알 수 있음" },
  { hanja: "一瀉千里", hangul: "일사천리", meaning: "일이 거침없이 빨리 진행됨" },
  { hanja: "一石二鳥", hangul: "일석이조", meaning: "한 가지 일로 두 가지 이득을 봄" },
  { hanja: "一觸卽發", hangul: "일촉즉발", meaning: "조금만 건드려도 터질 듯한 몹시 위급한 상태" },
  { hanja: "日就月將", hangul: "일취월장", meaning: "나날이 다달이 발전함" },
  { hanja: "一片丹心", hangul: "일편단심", meaning: "변치 않는 참된 마음" },
  { hanja: "一喜一悲", hangul: "일희일비", meaning: "기쁨과 슬픔이 번갈아 일어남" },
  { hanja: "臨機應變", hangul: "임기응변", meaning: "그때그때 형편에 맞게 알맞게 대처함" },
  { hanja: "自手成家", hangul: "자수성가", meaning: "물려받은 것 없이 제 힘으로 살림을 이룸" },
  { hanja: "自業自得", hangul: "자업자득", meaning: "자기가 저지른 일의 결과를 자기가 받음" },
  { hanja: "自暴自棄", hangul: "자포자기", meaning: "절망에 빠져 스스로를 포기하고 돌보지 않음" },
  { hanja: "自畫自讚", hangul: "자화자찬", meaning: "자기가 한 일을 스스로 자랑함" },
  { hanja: "作心三日", hangul: "작심삼일", meaning: "굳게 먹은 마음이 사흘을 가지 못함" },
  { hanja: "賊反荷杖", hangul: "적반하장", meaning: "잘못한 사람이 도리어 잘못 없는 사람을 나무람" },
  { hanja: "適者生存", hangul: "적자생존", meaning: "환경에 가장 잘 적응하는 것만이 살아남음" },
  { hanja: "前代未聞", hangul: "전대미문", meaning: "이제까지 들어 본 적이 없음" },
  { hanja: "戰戰兢兢", hangul: "전전긍긍", meaning: "몹시 두려워 벌벌 떨며 조심함" },
  { hanja: "轉禍爲福", hangul: "전화위복", meaning: "재앙이 바뀌어 오히려 복이 됨" },
  { hanja: "切磋琢磨", hangul: "절차탁마", meaning: "학문과 덕행을 부지런히 갈고닦음" },
  { hanja: "絶體絶命", hangul: "절체절명", meaning: "살아날 길이 없는 막다른 처지" },
  { hanja: "切齒腐心", hangul: "절치부심", meaning: "몹시 분하여 이를 갈며 속을 썩임" },
  { hanja: "漸入佳境", hangul: "점입가경", meaning: "갈수록 더욱 좋거나 재미있어짐" },
  { hanja: "糟糠之妻", hangul: "조강지처", meaning: "가난하고 힘들 때 함께 고생한 아내" },
  { hanja: "朝三暮四", hangul: "조삼모사", meaning: "눈앞의 차이만 알고 결과가 같음을 모름, 또는 잔꾀로 남을 속임" },
  { hanja: "鳥足之血", hangul: "조족지혈", meaning: "새 발의 피처럼 아주 적은 분량" },
  { hanja: "左顧右眄", hangul: "좌고우면", meaning: "이쪽저쪽 돌아보며 결정을 망설임" },
  { hanja: "主客顚倒", hangul: "주객전도", meaning: "주된 것과 부차적인 것의 순서가 뒤바뀜" },
  { hanja: "晝耕夜讀", hangul: "주경야독", meaning: "낮에는 일하고 밤에는 공부하며 어렵게 배움" },
  { hanja: "走馬看山", hangul: "주마간산", meaning: "자세히 살피지 않고 대충 보고 지나감" },
  { hanja: "竹馬故友", hangul: "죽마고우", meaning: "어릴 때부터 함께 놀며 자란 벗" },
  { hanja: "衆口難防", hangul: "중구난방", meaning: "여러 사람이 마구 떠들어 막기 어려움" },
  { hanja: "支離滅裂", hangul: "지리멸렬", meaning: "이리저리 흩어지고 찢기어 갈피를 잡을 수 없음" },
  { hanja: "知彼知己", hangul: "지피지기", meaning: "상대를 알고 나를 앎" },
  { hanja: "進退兩難", hangul: "진퇴양난", meaning: "나아가지도 물러서지도 못하는 어려운 처지" },
  { hanja: "此日彼日", hangul: "차일피일", meaning: "오늘 내일 하며 자꾸 기한을 미룸" },
  { hanja: "天高馬肥", hangul: "천고마비", meaning: "하늘이 높고 말이 살찌는 좋은 계절, 가을" },
  { hanja: "千辛萬苦", hangul: "천신만고", meaning: "온갖 애를 쓰며 고생함" },
  { hanja: "千載一遇", hangul: "천재일우", meaning: "천 년에 한 번 만날 만큼 드문 좋은 기회" },
  { hanja: "天眞爛漫", hangul: "천진난만", meaning: "꾸밈없이 순진하고 천진함" },
  { hanja: "千篇一律", hangul: "천편일률", meaning: "개성 없이 모두 엇비슷함" },
  { hanja: "徹頭徹尾", hangul: "철두철미", meaning: "처음부터 끝까지 빈틈없이 철저함" },
  { hanja: "淸廉潔白", hangul: "청렴결백", meaning: "마음이 맑고 깨끗하며 재물 욕심이 없음" },
  { hanja: "靑天霹靂", hangul: "청천벽력", meaning: "맑은 하늘의 날벼락처럼 뜻밖에 닥친 큰일" },
  { hanja: "靑出於藍", hangul: "청출어람", meaning: "제자나 후배가 스승이나 선배보다 나음" },
  { hanja: "初志一貫", hangul: "초지일관", meaning: "처음 세운 뜻을 끝까지 밀고 나감" },
  { hanja: "寸鐵殺人", hangul: "촌철살인", meaning: "짧은 말로 핵심을 찔러 감동이나 깨우침을 줌" },
  { hanja: "秋風落葉", hangul: "추풍낙엽", meaning: "가을바람에 지는 잎처럼 세력이 힘없이 무너짐" },
  { hanja: "七顚八起", hangul: "칠전팔기", meaning: "여러 번 실패해도 굴하지 않고 다시 일어섬" },
  { hanja: "快刀亂麻", hangul: "쾌도난마", meaning: "복잡하게 얽힌 일을 명쾌하게 처리함" },
  { hanja: "他山之石", hangul: "타산지석", meaning: "남의 하찮은 언행도 자신을 닦는 데 도움이 됨" },
  { hanja: "卓上空論", hangul: "탁상공론", meaning: "현실성 없는 허황한 논의" },
  { hanja: "泰然自若", hangul: "태연자약", meaning: "어떤 일에도 흔들림 없이 태연함" },
  { hanja: "破竹之勢", hangul: "파죽지세", meaning: "대나무를 쪼개듯 거침없이 나아가는 기세" },
  { hanja: "八方美人", hangul: "팔방미인", meaning: "여러 방면에 두루 능통한 사람" },
  { hanja: "表裏不同", hangul: "표리부동", meaning: "겉과 속이 다름" },
  { hanja: "風前燈火", hangul: "풍전등화", meaning: "바람 앞의 등불처럼 매우 위태로운 처지" },
  { hanja: "皮骨相接", hangul: "피골상접", meaning: "살가죽과 뼈가 맞붙을 만큼 몹시 여윔" },
  { hanja: "鶴首苦待", hangul: "학수고대", meaning: "학처럼 목을 길게 빼고 몹시 기다림" },
  { hanja: "咸興差使", hangul: "함흥차사", meaning: "심부름을 가서 소식이 없거나 늦게 오는 사람" },
  { hanja: "虛心坦懷", hangul: "허심탄회", meaning: "거리낌 없이 속마음을 터놓음" },
  { hanja: "螢雪之功", hangul: "형설지공", meaning: "어려운 형편에서도 부지런히 학문을 닦은 보람" },
  { hanja: "好事多魔", hangul: "호사다마", meaning: "좋은 일에는 방해가 되는 일이 많음" },
  { hanja: "虎視眈眈", hangul: "호시탐탐", meaning: "기회를 노리며 형세를 살핌" },
  { hanja: "畫龍點睛", hangul: "화룡점정", meaning: "가장 중요한 부분을 마무리하여 일을 완성함" },
  { hanja: "畫蛇添足", hangul: "화사첨족", meaning: "쓸데없는 일을 덧붙이다가 도리어 일을 그르침" },
  { hanja: "換骨奪胎", hangul: "환골탈태", meaning: "몰라볼 만큼 새롭게 달라짐" },
  { hanja: "橫說竪說", hangul: "횡설수설", meaning: "조리 없이 이 말 저 말 마구 늘어놓음" },
  { hanja: "厚顔無恥", hangul: "후안무치", meaning: "뻔뻔스러워 부끄러움을 모름" },
  { hanja: "喜怒哀樂", hangul: "희로애락", meaning: "기쁨과 노여움과 슬픔과 즐거움" },
];
